import crypto from "node:crypto";
import { coreApi } from "./client.js";
import { isAlreadyExists, isNotFound } from "./errors.js";
import { logger } from "../lib/logger.js";

export interface StoreSecrets {
  secretName: string;
  mariadbRootPassword: string;
  mariadbPassword: string;
  mariadbReplicationPassword: string;
  wordpressPassword: string;
  /** True when the existing Secret was reused (a retry) rather than generated on this run. */
  reused: boolean;
}

/**
 * Keys required by the Bitnami WordPress + MariaDB subcharts we install:
 * - `wordpress-password`              -> wordpress.existingSecret
 * - `mariadb-root-password`           -> wordpress.mariadb.auth.existingSecret
 * - `mariadb-password`                -> wordpress.mariadb.auth.existingSecret
 * - `mariadb-replication-password`    -> wordpress.mariadb.auth.existingSecret
 */
const SECRET_KEYS = [
  "mariadb-root-password",
  "mariadb-password",
  "mariadb-replication-password",
  "wordpress-password",
] as const;

type SecretKey = (typeof SECRET_KEYS)[number];

function generatePassword(length = 24): string {
  return crypto.randomBytes(length).toString("base64url").slice(0, length);
}

function credentialsFromSecret(
  secretName: string,
  data: Record<string, string>
): Omit<StoreSecrets, "reused"> {
  const missing = SECRET_KEYS.filter((key) => !data[key]);
  if (missing.length > 0) {
    throw new Error(
      `Secret "${secretName}" is missing required keys: ${missing.join(", ")}. ` +
        `Refusing to regenerate credentials; delete the store to provision a fresh one.`
    );
  }

  const decode = (key: SecretKey) => Buffer.from(data[key], "base64").toString("utf8");

  return {
    secretName,
    mariadbRootPassword: decode("mariadb-root-password"),
    mariadbPassword: decode("mariadb-password"),
    mariadbReplicationPassword: decode("mariadb-replication-password"),
    wordpressPassword: decode("wordpress-password"),
  };
}

/**
 * Credentials are the one thing that must never be regenerated by a retry: rotating the
 * MariaDB password of a running store would lock WordPress out of its own database.
 * So: reuse the existing secret whenever it is present, create it only on first provision.
 */
export async function ensureStoreSecrets(
  namespace: string,
  secretName = "store-credentials"
): Promise<StoreSecrets> {
  try {
    const existing = await coreApi.readNamespacedSecret({ name: secretName, namespace });
    logger.info({ namespace, secretName }, "store_credentials_reused");
    return { ...credentialsFromSecret(secretName, existing.data ?? {}), reused: true };
  } catch (err) {
    if (!isNotFound(err)) throw err;
  }

  const generated: Record<SecretKey, string> = {
    "mariadb-root-password": generatePassword(),
    "mariadb-password": generatePassword(),
    "mariadb-replication-password": generatePassword(),
    "wordpress-password": generatePassword(),
  };

  try {
    await coreApi.createNamespacedSecret({
      namespace,
      body: {
        metadata: {
          name: secretName,
          labels: {
            "app.kubernetes.io/managed-by": "urumi",
            "app.kubernetes.io/part-of": "urumi",
          },
        },
        type: "Opaque",
        stringData: generated,
      },
    });
    logger.info({ namespace, secretName }, "store_credentials_created");
    return {
      reused: false,
      secretName,
      mariadbRootPassword: generated["mariadb-root-password"],
      mariadbPassword: generated["mariadb-password"],
      mariadbReplicationPassword: generated["mariadb-replication-password"],
      wordpressPassword: generated["wordpress-password"],
    };
  } catch (err) {
    // Another reconciliation run created it first: reuse theirs, never overwrite.
    if (!isAlreadyExists(err)) throw err;
    const raced = await coreApi.readNamespacedSecret({ name: secretName, namespace });
    logger.info({ namespace, secretName }, "store_credentials_reused");
    return { ...credentialsFromSecret(secretName, raced.data ?? {}), reused: true };
  }
}
