apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "urumi.fullname" . }}-api
  labels:
    {{- include "urumi.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "urumi.fullname" . }}-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "urumi.fullname" . }}-api
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "urumi.fullname" . }}-api
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "urumi.fullname" . }}-config
            - secretRef:
                name: {{ include "urumi.fullname" . }}-db
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
