apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "urumi.fullname" . }}-config
  labels:
    {{- include "urumi.labels" . | nindent 4 }}
data:
  STORE_DOMAIN: {{ .Values.api.env.STORE_DOMAIN | quote }}
  HELM_CHART_PATH: {{ .Values.api.env.HELM_CHART_PATH | quote }}
  MAX_STORES: {{ .Values.api.env.MAX_STORES | quote }}
  MAX_CONCURRENT_PROVISIONS: {{ .Values.api.env.MAX_CONCURRENT_PROVISIONS | quote }}
  NODE_ENV: {{ .Values.api.env.NODE_ENV | quote }}
  PORT: {{ .Values.api.port | quote }}
