apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medusa
  labels:
    {{- include "medusa-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: medusa
spec:
  type: {{ .Values.medusa.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-medusa
